USE weatherforum_db;
INSERT INTO weather_inputs (user_name, blog_title, city_name, state_name, country_name, weather_condition, weather_input) VALUES ('LoriS', 'Flash flood watch until tomrrow 6AM', 'Mission Viejo', 'CA','US','Flooding', 'Flash flood watch Raining hard at 6PM. Current temperature: 52 degrees F low: 50 degrees F');
USE weatherforum_db;
INSERT INTO weather_inputs (user_name, blog_title, city_name, state_name, country_name, weather_condition, weather_input) VALUES ('ColinB', 'Light rain here','Raining', 'Irvine', 'CA','US','Raining', 'Light rain at 3PM. Current temperature: 56 degrees F, low: 52 degrees F');
USE weatherforum_db;
INSERT INTO weather_inputs (user_name, blog_title, city_name, state_name, country_name, weather_condition, weather_input) VALUES ('MissyL', 'Love the sun!', 'New York', 'NY','US','Sunny', 'Sunny all day. Current temperature: 35 degrees F low: 25 degrees F');
USE weatherforum_db;
INSERT INTO weather_inputs (user_name, blog_title, city_name, state_name, country_name, weather_condition, weather_input) VALUES ('TaeyoungK', 'Snow, snow, snow!', 'Seoul', '','KR', 'Snowing', 'Cloudy. Current temperature: 33 degrees F low: 12 degrees F');
USE weatherforum_db;
INSERT INTO weather_inputs (user_name, blog_title, city_name, state_name, country_name, weather_condition, weather_input) VALUES ('Pierre', 'Very humid in Paris!', 'Paris', '','FR','Humid', 'Partly cloudy and humid. Current temperature: 48 degrees F low: 38 degrees F');
USE weatherforum_db;
INSERT INTO weather_inputs (user_name, blog_title, city_name, state_name, country_name, weather_condition, weather_input) VALUES ('HarryP', 'Very humid in Paris!', 'Seattle', 'WA','','Lightning', 'Thunder and a LOT of lightning locally <1mi away). Current temperature: 48 degrees F low: 38 degrees F');